### ISSUE TITLE
Uni-Perceiver-MoE on NIPS2022

### ISSUE THREAD

**Issue by Lechatelia** [codecaution/Awesome-Mixture-of-Experts-Papers#10]
Hey! Thank you for your work.
Could you add our MoE work for generalist models in NIPS 2022？ 
Uni-Perceiver-MoE: Learning Sparse Generalist Models with Conditional MoEs. [[paper]](https://arxiv.org/abs/2206.04674) [[code]](https://github.com/fundamentalvision/Uni-Perceiver)
This work uses MoE to mitigate task interference in multitask training and proposes routing strategies to make MoE more efficient.

Thank you so much!

**Comment by codecaution** [comment]
Thanks for your suggestion and I have already added it.
