### ISSUE TITLE
Three new papers about MoE

### ISSUE THREAD

**Issue by XueFuzhao** [codecaution/Awesome-Mixture-of-Experts-Papers#6]
Hi authors, 
Thank you for your repo! I also created one awesome MoE repo recently. I will update your new work into my repo.  
https://github.com/XueFuzhao/awesome-mixture-of-experts
Also, I think a few of my papers are missing. 
Go Wider Instead of Deeper [[AAAI2022]](https://arxiv.org/abs/2107.11817)
Cross-token Modeling with Conditional Computation [[5 Sep 2021]](https://arxiv.org/abs/2109.02008)
One Student Knows All Experts Know: From Sparse to Dense [[26 Jan 2022]](https://arxiv.org/abs/2201.10890)

Thank you so much!

**Comment by codecaution** [comment]
Hi, XueFu. 
Thanks for your suggestions!
I have already added your papers in my list and add the contents section as your repo.

Please also include our system paper HetuMoE:
**HetuMoE: An Efficient Trillion-scale Mixture-of-Expert Distributed Training System** [[pdf]](https://arxiv.org/abs/2203.14685) [[github](https://github.com/PKU-DAIR/Hetu)]
Thanks!

**Comment by XueFuzhao** [comment]
No problem! Done
