### ISSUE TITLE
FasterMoE paper on PPoPP'22

### ISSUE THREAD

**Issue by laekov** [codecaution/Awesome-Mixture-of-Experts-Papers#7]
There is a new distributed system *FasterMoE: modeling and optimizing training of large-scale dynamic pre-trained models* published on [PPoPP'22](https://dl.acm.org/doi/abs/10.1145/3503221.3508418). Please kindly consider including this paper in your list.

FYI, we have also included your MoE systems and paper collections on [FastMoE's homepage](https://fastmoe.ai/documentation/related-works.html#moe-paper-collections)

**Comment by codecaution** [comment]
Thanks for your suggestions!
